### ISSUE TITLE
syntax error in shell script

### ISSUE THREAD

**Issue by ljm42** [andre-richter/vfio-pci-bind#1]
I believe this line in the shell script is incorrect:
https://github.com/andre-richter/vfio-pci-bind/blob/ca6b6607908fa91df5b0aaff3c1eb027a103ea0d/vfio-pci-bind.sh#L110

In the Bourne Shell the "-ne" operator is meant for integer operations, since this is a string operation it should use "!=" or "==", right?

Also, it looks like the logic is reversed. Based on what the script is doing, and the corresponding line in the Ruby file:
https://github.com/andre-richter/vfio-pci-bind/blob/ca6b6607908fa91df5b0aaff3c1eb027a103ea0d/vfio-pci-bind.rb#L103

I believe this line should be:
```if [[ "$curr_driver" == "vfio-pci" ]]; then```

Can you double check and see if I am off base here?

**Comment by andre-richter** [comment]
> I believe this line should be:
> `if [[ "$curr_driver" == "vfio-pci" ]]; then`
> 
> Can you double check and see if I am off base here?

Good catch. I agree with your assessment.

**Comment by andre-richter** [comment]
Solved by #2
