### ISSUE TITLE
bind specific Vendor:Device

### ISSUE THREAD

**Issue by ljm42** [andre-richter/vfio-pci-bind#3]
Thanks for this script. It works well until you add hardware that changes your PCI addresses, and then there is a risk that the wrong device will be bound to vfio-pci. It would be a big problem if the host lost access to a nic or drive controller as a result.

I'd like to propose that the script accept a second (optional) parameter of the `Vendor:Device` to bind. If the supplied `Vendor:Device` is found at  `Domain:Bus:Device.Function`, then it can go ahead and bind the device. If something else is found at that address then it should not bind the device.

I will submit a pull request for a potential implementation of this.

**Comment by andre-richter** [comment]
Interesting use case. One question: If you are unsure if the `Vendor:Device` device lives at the supplied domain address, why not parse the whole PCIe tree first to find it, and use the result to bind it with the current algorithm?

**Comment by ljm42** [comment]
The difficulty is if you have two pieces of the same hardware, they will share the `Vendor:Device` code. 

For instance, my motherboard has two Intel nics:
```
#lspci -n -d 8086:1533
02:00.0 0200: 8086:1533 (rev 03)
03:00.0 0200: 8086:1533 (rev 03)
```
(each with their own IOMMU group) so I need the pci address to distinguish them.

I thought about switching it and making the `Vendor:Device` be the required field and `Domain:Bus:Device.Function` be optional, but that would be a pretty invasive change and I didn't want to break backward compatibility.

Hmm... I suppose we don't *have* to break backward compatibility since we have regexes that can distinguish which parameter is which.  It wouldn't be that invasive either... if you pass in just a `Vendor:Device` code we could use lcpci to determine the `Domain:Bus:Device.Function` and then the script can continue.

I'll take a crack at that.

The question is what should happen if you just pass a `Vendor:Device` code and there are multiple results:
1. bind the first one
2. loop through and bind them all
3. throw an error and require you to specify a pci address too

I think I'll go with option 3.

**Comment by andre-richter** [comment]
> Hmm... I suppose we don't _have_ to break backward compatibility since we have regexes that can distinguish which parameter is which. It wouldn't be that invasive either... if you pass in just a `Vendor:Device` code we could use lcpci to determine the `Domain:Bus:Device.Function` and then the script can continue.

Should work. B:D.F and Vendor:Device can be distinguished fast through the "`.`" character.

> I'll take a crack at that.
> 
> The question is what should happen if you just pass a `Vendor:Device` code and there are multiple results:
> 
>     1. bind the first one
> 
>     2. loop through and bind them all
> 
>     3. throw an error and require you to specify a pci address too
> 
> 
> I think I'll go with option 3.

Agree with 3.

By the way, are you planning on keeping the Ruby script in sync too?

**Comment by ljm42** [comment]
I like this!
* If the user has a single `Vendor:Device`, they can provide that and it will be bound regardless of how the PCI address might change
* If they have multiple `Vendor:Device`s, they can provide the `Domain:Bus:Device.Function` for the one they want to bind
* For backwards compatibility, they can also provide a `Domain:Bus:Device.Function` to bind

What do you think, do you see any issues?

I'm sorry that I have no experience with Ruby, are you up for syncing the changes there?

**Comment by andre-richter** [comment]
Actually, I think the ruby user base for this script would be very minimal. We can just delete it for now and see if someone complains. 

Would be great if you can add that to your PR please?

**Comment by ljm42** [comment]
Sure thing. I also added more detail to the readme

**Comment by andre-richter** [comment]
Awesome, thanks, is this complete and tested from your side now? I won’t have time to test it myself the next few days. But if you say it’s good to go I’ll just merge it 👍

**Comment by ljm42** [comment]
I believe this is good to go. But I have limited hardware to test on, I don't mind waiting until you've had a chance to smoke test it.

**Comment by andre-richter** [comment]
Thanks for all your work! Merged it 👍

**Comment by ljm42** [comment]
Great! Thanks!
